steps:
  # Pull image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: [ "-c" , "docker pull gcr.io/${PROJECT_ID}/bingo-api:latest || exit 0" ]

  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/bingo-api",
        "--cache-from",
        "gcr.io/${PROJECT_ID}/bingo-api:latest",
        "."
    ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/${PROJECT_ID}/bingo-api" ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
          "run",
          "deploy",
          "bingo-api",
          "--image",
          "gcr.io/${PROJECT_ID}/bingo-api",
          "--region",
          "us-central1",
          "--platform",
          "managed",
          "--allow-unauthenticated",
      ]

  # Force the new revision to serve 100% of traffic.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
          "run",
          "services",
          "update-traffic",
          "bingo-api",
          "--to-latest",
          "--platform",
          "managed",
          "--region",
          "us-central1",
      ]

images:
  - "gcr.io/${PROJECT_ID}/bingo-api"

options:
  logging: CLOUD_LOGGING_ONLY
