steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/ebombo-events/bingo-dev-api", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/ebombo-events/bingo-dev-api"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "bingo-dev-api",
        "--image",
        "gcr.io/ebombo-events/bingo-dev-api",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
images:
  - "gcr.io/ebombo-events/bingo-dev-api"
options:
  logging: CLOUD_LOGGING_ONLY
